# Generated by Django 3.1.2 on 2020-10-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201011_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='item',
            field=models.ManyToManyField(related_name='watchlist_items', to='auctions.Listing'),
        ),
    ]
