# Generated by Django 3.1.2 on 2020-10-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201014_2103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
